feat: Xcode File Templates 도입
YAPP-Github/WeSpot-iOS pull request #6
Opened 2024-06-14 05:49 UTC by agseou

## Xcode File Templates 도입

- [ ] ViewController(Feature), ViewModel(Reator)에 관한 Xcode File Templates을 추가했습니다.
- [ ] makeFile에 설정한 `make templates' 명령어를 통해 Xcode에 접근해 설치할 수 있습니다.
<br/>

## 화면
<img height="300" alt="파일 생성 창" src="https://github.com/YAPP-Github/24th-App-Team-1-iOS/assets/108851660/856ba7c2-f036-41b0-b9ee-61b229f34d98">

File > New > File... (⌘ N) 입력 시, 뜨는 파일 생성 창 가장 최하단에서 Feature Template을 찾을 수 있습니다.<br/><br/>
<img width="118" alt="파일 생성 결과 이미지" src="https://github.com/YAPP-Github/24th-App-Team-1-iOS/assets/108851660/c64d4851-4e2d-43da-b0be-0927525b410d">
생성 시 접두어는 동일한 이름으로 설정됩니다.

### **templates를 재설치했을 경우, Xcode를 완전히 종료하고 열어야 적용됩니다.**

<br/>

## 레퍼런스
[Custom Xcode File Templates](https://ios-development.tistory.com/760)

<br/>
close: #5

2024-06-15 12:44 UTC, Do-hyun-Kim requested changes

2024-06-15 12:44 UTC, Do-hyun-Kim commented on 24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Feature.swift
> +class ___FILEBASENAMEASIDENTIFIER___: BaseViewController<Reactor> {
해당 템플릿에 정의된 `class`는 해당 Feature에서만 사용하기 때문에 `final` 키워드를 명시해서 런타임 속도를 향상 시키는 것이 좋을 것 같습니다.

- [참고 레퍼런스](https://tdcian.tistory.com/303)

2024-06-15 12:44 UTC, Do-hyun-Kim commented on 24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Reactor.swift
> +class ___FILEBASENAMEASIDENTIFIER___: Reactor {
`Reactor` class도 동일합니다. 이 부분도 `override`를 하는 경우가 없기 때문에 `final` 키워드를 명시 하는 것이 좋습니다. :)

2024-06-16 03:33 UTC, agseou commented on 24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Feature.swift
> +class ___FILEBASENAMEASIDENTIFIER___: BaseViewController<Reactor> {
final 접근제어자 템플릿에 반영했습니다!

2024-06-16 03:33 UTC, agseou commented on 24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Reactor.swift
> +class ___FILEBASENAMEASIDENTIFIER___: Reactor {
수고하셨습니다 :)

2024-06-16 08:37 UTC, Do-hyun-Kim approved these changes
Xcode Templates 작업하느라 수고하셨습니다!! 👍👍

2024-06-16 14:18 UTC, merged